// <auto-generated />
using System;
using Hospital_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Web.Migrations
{
    [DbContext(typeof(Hospital_WebContext))]
    [Migration("20250512211138_InitialMigration2")]
    partial class InitialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Web.Models.Consulta", b =>
                {
                    b.Property<int>("Episodio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Episodio"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GabineteID")
                        .HasColumnType("int");

                    b.Property<int>("Gabinete_Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int?>("MedicoN_Processo")
                        .HasColumnType("int");

                    b.Property<int>("Medico_Id")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Tratamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Utente_Id")
                        .HasColumnType("int");

                    b.HasKey("Episodio");

                    b.HasIndex("GabineteID");

                    b.HasIndex("Gabinete_Id");

                    b.HasIndex("MedicoN_Processo");

                    b.HasIndex("Medico_Id");

                    b.HasIndex("Utente_Id");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("Hospital_Web.Models.Internamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("Consulta_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Hora_Entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data_Hora_Saida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quarto_Id")
                        .HasColumnType("int");

                    b.Property<int>("Utente_Id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Consulta_Id");

                    b.HasIndex("Quarto_Id");

                    b.HasIndex("Utente_Id");

                    b.ToTable("Internamento");
                });

            modelBuilder.Entity("Hospital_Web.Models.LimpezaSala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("Funcionario_Id")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("Produto1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Produto2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Produto3")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sala_Id")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Funcionario_Id");

                    b.HasIndex("Sala_Id");

                    b.ToTable("LimpezaSala");
                });

            modelBuilder.Entity("Hospital_Web.Models.Pessoa", b =>
                {
                    b.Property<int>("N_Processo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("N_Processo"));

                    b.Property<string>("Cod_postal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Data_de_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone2")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("N_Processo");

                    b.ToTable("Pessoa");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Hospital_Web.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Andar")
                        .HasColumnType("int");

                    b.Property<string>("Bloco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sala");

                    b.HasDiscriminator().HasValue("Sala");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hospital_Web.Models.Utilizador", b =>
                {
                    b.Property<int>("ID_Utilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Utilizador"));

                    b.Property<DateTime>("Data_Criacao_Conta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome_Utilizador")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Pessoa_Id")
                        .HasColumnType("int");

                    b.HasKey("ID_Utilizador");

                    b.HasIndex("Pessoa_Id")
                        .IsUnique()
                        .HasFilter("[Pessoa_Id] IS NOT NULL");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("Hospital_Web.Models.FuncionarioLimpeza", b =>
                {
                    b.HasBaseType("Hospital_Web.Models.Pessoa");

                    b.Property<string>("Certificacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Data_de_contratacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tamanho_Uniforme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("FuncionarioLimpeza");
                });

            modelBuilder.Entity("Hospital_Web.Models.Medico", b =>
                {
                    b.HasBaseType("Hospital_Web.Models.Pessoa");

                    b.Property<int>("Anos_de_experiencia")
                        .HasColumnType("int");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numero_de_ordem")
                        .HasColumnType("int");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("Hospital_Web.Models.Utente", b =>
                {
                    b.HasBaseType("Hospital_Web.Models.Pessoa");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("Data_de_Registo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado_clinico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Grupo_Sanguineo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Medico_Associado_Id")
                        .HasColumnType("int");

                    b.Property<string>("Seguro_de_Saude")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("Medico_Associado_Id");

                    b.ToTable("Utente");
                });

            modelBuilder.Entity("Hospital_Web.Models.Gabinete", b =>
                {
                    b.HasBaseType("Hospital_Web.Models.Sala");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Equipamento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.ToTable("Sala", t =>
                        {
                            t.Property("Descricao")
                                .HasColumnName("Gabinete_Descricao");
                        });

                    b.HasDiscriminator().HasValue("Gabinete");
                });

            modelBuilder.Entity("Hospital_Web.Models.QuartosInternagem", b =>
                {
                    b.HasBaseType("Hospital_Web.Models.Sala");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("QuartosInternagem");
                });

            modelBuilder.Entity("Hospital_Web.Models.Consulta", b =>
                {
                    b.HasOne("Hospital_Web.Models.Gabinete", null)
                        .WithMany("Consultas")
                        .HasForeignKey("GabineteID");

                    b.HasOne("Hospital_Web.Models.Gabinete", "Gabinete")
                        .WithMany()
                        .HasForeignKey("Gabinete_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hospital_Web.Models.Medico", null)
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoN_Processo");

                    b.HasOne("Hospital_Web.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("Medico_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hospital_Web.Models.Utente", "Utente")
                        .WithMany("Consultas")
                        .HasForeignKey("Utente_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gabinete");

                    b.Navigation("Medico");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Hospital_Web.Models.Internamento", b =>
                {
                    b.HasOne("Hospital_Web.Models.Consulta", "Consulta")
                        .WithMany()
                        .HasForeignKey("Consulta_Id");

                    b.HasOne("Hospital_Web.Models.QuartosInternagem", "Quarto")
                        .WithMany("Internamentos")
                        .HasForeignKey("Quarto_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Web.Models.Utente", "Utente")
                        .WithMany("Internamentos")
                        .HasForeignKey("Utente_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Quarto");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Hospital_Web.Models.LimpezaSala", b =>
                {
                    b.HasOne("Hospital_Web.Models.FuncionarioLimpeza", "Funcionario")
                        .WithMany("LimpezasDeSala")
                        .HasForeignKey("Funcionario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Web.Models.Sala", "Sala")
                        .WithMany("LimpezasDeSala")
                        .HasForeignKey("Sala_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Hospital_Web.Models.Utilizador", b =>
                {
                    b.HasOne("Hospital_Web.Models.Pessoa", "Pessoa")
                        .WithOne("User")
                        .HasForeignKey("Hospital_Web.Models.Utilizador", "Pessoa_Id");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Hospital_Web.Models.FuncionarioLimpeza", b =>
                {
                    b.HasOne("Hospital_Web.Models.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Web.Models.FuncionarioLimpeza", "N_Processo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Web.Models.Medico", b =>
                {
                    b.HasOne("Hospital_Web.Models.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Web.Models.Medico", "N_Processo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Web.Models.Utente", b =>
                {
                    b.HasOne("Hospital_Web.Models.Medico", "MedicoAssociado")
                        .WithMany("UtentesAssociados")
                        .HasForeignKey("Medico_Associado_Id");

                    b.HasOne("Hospital_Web.Models.Pessoa", null)
                        .WithOne()
                        .HasForeignKey("Hospital_Web.Models.Utente", "N_Processo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicoAssociado");
                });

            modelBuilder.Entity("Hospital_Web.Models.Pessoa", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Hospital_Web.Models.Sala", b =>
                {
                    b.Navigation("LimpezasDeSala");
                });

            modelBuilder.Entity("Hospital_Web.Models.FuncionarioLimpeza", b =>
                {
                    b.Navigation("LimpezasDeSala");
                });

            modelBuilder.Entity("Hospital_Web.Models.Medico", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("UtentesAssociados");
                });

            modelBuilder.Entity("Hospital_Web.Models.Utente", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("Internamentos");
                });

            modelBuilder.Entity("Hospital_Web.Models.Gabinete", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("Hospital_Web.Models.QuartosInternagem", b =>
                {
                    b.Navigation("Internamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
